package com.cris.station_master.paths;

import com.orchestranetworks.schema.*;

/**
 * Generated by TIBCO EBX(R) 1214:0002, at 2023/03/22 23:14:01 [CET].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: station_master, path: /WEB-INF/ebx/schemas/station_master_data_model.xsd].
 * 
 * Root paths in this interface: 
 * 	'/root'   relativeToRoot: false
 * 
 */
public interface StationPaths
{
	// ===============================================
	// Constants for nodes under '/root'.
	// Statistics:
	//		48 path constants.
	//		36 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Root_Station
	{
		private static final Path _Root_Station = _Root.add("Station");
		public static Path getPathInSchema()
		{
			return _Root_Station;
		}
		public static final Path _Root_Station_Station_Code = Path.parse("./Station_Code");
		public static final Path _Root_Station_Station_Numeric_Code = Path.parse("./Station_Numeric_Code");
		public static final Path _Root_Station_Station_Name = Path.parse("./Station_Name");
		public static final Path _Root_Station_Station_Hindi_Name = Path.parse("./Station_Hindi_Name");
		public static final Path _Root_Station_Station_Short_Name = Path.parse("./Station_Short_Name");
		public static final Path _Root_Station_Zone_Code = Path.parse("./Zone_Code");
		public static final Path _Root_Station_Division_Code = Path.parse("./Division_Code");
		public static final Path _Root_Station_Station_Valid_From = Path.parse("./Station_Valid_From");
		public static final Path _Root_Station_Station_Valid_Upto = Path.parse("./Station_Valid_Upto");
		public static final Path _Root_Station_Latitude = Path.parse("./Latitude");
		public static final Path _Root_Station_Longitude = Path.parse("./Longitude");
		public static final Path _Root_Station_Traffic_Type = Path.parse("./Traffic_Type");
		public static final Path _Root_Station_Transhipment_Flag = Path.parse("./Transhipment_Flag");
		public static final Path _Root_Station_Gauge_Code = Path.parse("./Gauge_Code");
		public static final Path _Root_Station_Station_Class = Path.parse("./Station_Class");
		public static final Path _Root_Station_Junction_Flag = Path.parse("./Junction_Flag");
		public static final Path _Root_Station_Interchange_Flag = Path.parse("./Interchange_Flag");
		public static final Path _Root_Station_State = Path.parse("./State");
		public static final Path _Root_Station_Pincode = Path.parse("./Pincode");
		public static final Path _Root_Station_District = Path.parse("./District");
		public static final Path _Root_Station_Tehsil = Path.parse("./Tehsil");
		public static final Path _Root_Station_Station_Category = Path.parse("./Station_Category");
		public static final Path _Root_Station_Interlocking_Standard = Path.parse("./Interlocking_Standard");
		public static final Path _Root_Station_Traction = Path.parse("./Traction");
		public static final Path _Root_Station_Working_Division = Path.parse("./Working_Division");
		public static final Path _Root_Station_No_Of_Lines = Path.parse("./No_Of_Lines");
		public static final Path _Root_Station_Weight_Bridge = Path.parse("./Weight_Bridge");
		public static final Path _Root_Station_Siding = Path.parse("./Siding");
		public static final Path _Root_Station_Block_Section = Path.parse("./Block_Section");
		public static final Path _Root_Station_Booking_Type = Path.parse("./Booking_Type");
		public static final Path _Root_Station_Operating_Station_Signal = Path.parse("./Operating_Station_Signal");
		public static final Path _Root_Station_Is_Station_Functional = Path.parse("./Is_Station_Functional");
		public static final Path _Root_Station_Booking_Resource = Path.parse("./Booking_Resource");
		public static final Path _Root_Station_Audit_Info = Path.parse("./Audit_Info");
		public static final Path _Root_Station_Audit_Info_Source_Record_Id = Path.parse("./Audit_Info/Source_Record_Id");
		public static final Path _Root_Station_Audit_Info_Source_System_Name = Path.parse("./Audit_Info/Source_System_Name");
		public static final Path _Root_Station_Audit_Info_Source_Event_Type = Path.parse("./Audit_Info/Source_Event_Type");
	} 
	// ===============================================

}
