package com.bct.addon.dxch.path;

import com.orchestranetworks.schema.*;

/**
 * Generated by TIBCO EBX(R) 1216:0002, at 2023/09/08 19:08:31 [CEST].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: svAutomation, path: /WEB-INF/ebx/schemas/scadAlteryxMangement.xsd].
 * 
 * Root paths in this interface: 
 * 	'/root'   relativeToRoot: false
 * 
 */
public interface AlteryxMangPath
{
	// ===============================================
	// Constants for nodes under '/root'.
	// Prefix:  ''.
	// Statistics:
	//		154 path constants.
	//		65 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _AlteryxSVAutomation
	{
		private static final Path _AlteryxSVAutomation = _Root.add("AlteryxSVAutomation");
		public static Path getPathInSchema()
		{
			return _AlteryxSVAutomation;
		}
		public static final Path _AlteryxId = Path.parse("./alteryxId");
		public static final Path _WorkflowId = Path.parse("./workflowId");
		public static final Path _WorkflowName = Path.parse("./workflowName");
		public static final Path _Status = Path.parse("./status");
		public static final Path _AuditDetails = Path.parse("./auditDetails");
		public static final Path _AuditDetails_CreatedBy = Path.parse("./auditDetails/createdBy");
		public static final Path _AuditDetails_CreatedTimestamp = Path.parse("./auditDetails/createdTimestamp");
		public static final Path _AuditDetails_UpdatedBy = Path.parse("./auditDetails/updatedBy");
		public static final Path _AuditDetails_UpdatedTimestamp = Path.parse("./auditDetails/updatedTimestamp");
		public static final Path _AlteryxDatasets = Path.parse("./AlteryxDatasets");
		public static final Path _OutputSvs = Path.parse("./OutputSvs");
	} 

	// Table type path
	public final class _AlteryxDatasets
	{
		private static final Path _AlteryxDatasets = _Root.add("AlteryxDatasets");
		public static Path getPathInSchema()
		{
			return _AlteryxDatasets;
		}
		public static final Path _AlteryxId = Path.parse("./alteryxId");
		public static final Path _DatasetId = Path.parse("./datasetId");
		public static final Path _DatasetType = Path.parse("./datasetType");
		public static final Path _AuditDetails = Path.parse("./auditDetails");
		public static final Path _AuditDetails_CreatedBy = Path.parse("./auditDetails/createdBy");
		public static final Path _AuditDetails_CreatedTimestamp = Path.parse("./auditDetails/createdTimestamp");
		public static final Path _AuditDetails_UpdatedBy = Path.parse("./auditDetails/updatedBy");
		public static final Path _AuditDetails_UpdatedTimestamp = Path.parse("./auditDetails/updatedTimestamp");
	} 

	// Table type path
	public final class _DatasetsLookup
	{
		private static final Path _DatasetsLookup = _Root.add("DatasetsLookup");
		public static Path getPathInSchema()
		{
			return _DatasetsLookup;
		}
		public static final Path _DatasetId = Path.parse("./datasetId");
		public static final Path _DatasetName = Path.parse("./datasetName");
		public static final Path _Status = Path.parse("./status");
		public static final Path _WFID = Path.parse("./WFID");
		public static final Path _ParentDataspace = Path.parse("./parentDataspace");
		public static final Path _DataSet = Path.parse("./dataSet");
		public static final Path _DataModel = Path.parse("./dataModel");
		public static final Path _AuditDetails = Path.parse("./auditDetails");
		public static final Path _AuditDetails_CreatedBy = Path.parse("./auditDetails/createdBy");
		public static final Path _AuditDetails_CreatedTimestamp = Path.parse("./auditDetails/createdTimestamp");
		public static final Path _AuditDetails_UpdatedBy = Path.parse("./auditDetails/updatedBy");
		public static final Path _AuditDetails_UpdatedTimestamp = Path.parse("./auditDetails/updatedTimestamp");
		public static final Path _AlteryxDatasets = Path.parse("./alteryxDatasets");
	} 

	// Table type path
	public final class _OutputSvs
	{
		private static final Path _OutputSvs = _Root.add("OutputSvs");
		public static Path getPathInSchema()
		{
			return _OutputSvs;
		}
		public static final Path _AlteryxId = Path.parse("./alteryxId");
		public static final Path _SvId = Path.parse("./svId");
		public static final Path _AuditDetails = Path.parse("./auditDetails");
		public static final Path _AuditDetails_CreatedBy = Path.parse("./auditDetails/createdBy");
		public static final Path _AuditDetails_CreatedTimestamp = Path.parse("./auditDetails/createdTimestamp");
		public static final Path _AuditDetails_UpdatedBy = Path.parse("./auditDetails/updatedBy");
		public static final Path _AuditDetails_UpdatedTimestamp = Path.parse("./auditDetails/updatedTimestamp");
	} 

	// Table type path
	public final class _SVThemeLookup
	{
		private static final Path _SVThemeLookup = _Root.add("SVThemeLookup");
		public static Path getPathInSchema()
		{
			return _SVThemeLookup;
		}
		public static final Path _ThemeId = Path.parse("./themeId");
		public static final Path _ThemeName = Path.parse("./themeName");
		public static final Path _AuditDetails = Path.parse("./auditDetails");
		public static final Path _AuditDetails_CreatedBy = Path.parse("./auditDetails/createdBy");
		public static final Path _AuditDetails_CreatedTimestamp = Path.parse("./auditDetails/createdTimestamp");
		public static final Path _AuditDetails_UpdatedBy = Path.parse("./auditDetails/updatedBy");
		public static final Path _AuditDetails_UpdatedTimestamp = Path.parse("./auditDetails/updatedTimestamp");
		public static final Path _SVSubTheme = Path.parse("./SVSubTheme");
	} 

	// Table type path
	public final class _SVSubThemeLookup
	{
		private static final Path _SVSubThemeLookup = _Root.add("SVSubThemeLookup");
		public static Path getPathInSchema()
		{
			return _SVSubThemeLookup;
		}
		public static final Path _SubThemeId = Path.parse("./subThemeId");
		public static final Path _ThemeId = Path.parse("./themeId");
		public static final Path _SubThemeName = Path.parse("./subThemeName");
		public static final Path _AuditDetails = Path.parse("./auditDetails");
		public static final Path _AuditDetails_CreatedBy = Path.parse("./auditDetails/createdBy");
		public static final Path _AuditDetails_CreatedTimestamp = Path.parse("./auditDetails/createdTimestamp");
		public static final Path _AuditDetails_UpdatedBy = Path.parse("./auditDetails/updatedBy");
		public static final Path _AuditDetails_UpdatedTimestamp = Path.parse("./auditDetails/updatedTimestamp");
		public static final Path _SVProduct = Path.parse("./SVProduct");
	} 

	// Table type path
	public final class _SVProduct
	{
		private static final Path _SVProduct = _Root.add("SVProduct");
		public static Path getPathInSchema()
		{
			return _SVProduct;
		}
		public static final Path _ProductId = Path.parse("./productId");
		public static final Path _SubThemeId = Path.parse("./subThemeId");
		public static final Path _Product_Name = Path.parse("./Product_Name");
		public static final Path _AuditDetails = Path.parse("./auditDetails");
		public static final Path _AuditDetails_CreatedBy = Path.parse("./auditDetails/createdBy");
		public static final Path _AuditDetails_CreatedTimestamp = Path.parse("./auditDetails/createdTimestamp");
		public static final Path _AuditDetails_UpdatedBy = Path.parse("./auditDetails/updatedBy");
		public static final Path _AuditDetails_UpdatedTimestamp = Path.parse("./auditDetails/updatedTimestamp");
		public static final Path _SVLookup = Path.parse("./SVLookup");
	} 

	// Table type path
	public final class _SVLookup
	{
		private static final Path _SVLookup = _Root.add("SVLookup");
		public static Path getPathInSchema()
		{
			return _SVLookup;
		}
		public static final Path _SvId = Path.parse("./svId");
		public static final Path _ProductId = Path.parse("./productId");
		public static final Path _SvName = Path.parse("./svName");
		public static final Path _AuditDetails = Path.parse("./auditDetails");
		public static final Path _AuditDetails_CreatedBy = Path.parse("./auditDetails/createdBy");
		public static final Path _AuditDetails_CreatedTimestamp = Path.parse("./auditDetails/createdTimestamp");
		public static final Path _AuditDetails_UpdatedBy = Path.parse("./auditDetails/updatedBy");
		public static final Path _AuditDetails_UpdatedTimestamp = Path.parse("./auditDetails/updatedTimestamp");
		public static final Path _OutputSvs = Path.parse("./OutputSvs");
	} 
	// ===============================================

}
