package com.bct.addon.dxch.path;

import com.orchestranetworks.schema.*;

/**
 * Generated by TIBCO EBX(R) 1216:0002, at 2023/09/08 19:08:31 [CEST].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: dxchng, path: /WEB-INF/ebx/schemas/Category_Configuration.xsd].
 * 
 * Root paths in this interface: 
 * 	'/root'   relativeToRoot: false
 * 
 */
public interface CategoryConfigPath
{
	// ===============================================
	// Constants for nodes under '/root'.
	// Prefix:  ''.
	// Statistics:
	//		121 path constants.
	//		43 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Categories
	{
		private static final Path _Categories = _Root.add("Categories");
		public static Path getPathInSchema()
		{
			return _Categories;
		}
		public static final Path _ID = Path.parse("./ID");
		public static final Path _CategoryName = Path.parse("./categoryName");
		public static final Path _ReportingPeriod = Path.parse("./reportingPeriod");
		public static final Path _AuditDetails = Path.parse("./auditDetails");
		public static final Path _AuditDetails_CreatedBy = Path.parse("./auditDetails/createdBy");
		public static final Path _AuditDetails_CreatedTimestamp = Path.parse("./auditDetails/createdTimestamp");
		public static final Path _AuditDetails_UpdatedBy = Path.parse("./auditDetails/updatedBy");
		public static final Path _AuditDetails_UpdatedTimestamp = Path.parse("./auditDetails/updatedTimestamp");
		public static final Path _CategoryConfigurations = Path.parse("./CategoryConfigurations");
	} 

	// Table type path
	public final class _CategoryConfigurations
	{
		private static final Path _CategoryConfigurations = _Root.add("CategoryConfigurations");
		public static Path getPathInSchema()
		{
			return _CategoryConfigurations;
		}
		public static final Path _ID = Path.parse("./ID");
		public static final Path _CategoryID = Path.parse("./categoryID");
		public static final Path _Year = Path.parse("./year");
		public static final Path _Period = Path.parse("./period");
		public static final Path _AuditDetails = Path.parse("./auditDetails");
		public static final Path _AuditDetails_CreatedBy = Path.parse("./auditDetails/createdBy");
		public static final Path _AuditDetails_CreatedTimestamp = Path.parse("./auditDetails/createdTimestamp");
		public static final Path _AuditDetails_UpdatedBy = Path.parse("./auditDetails/updatedBy");
		public static final Path _AuditDetails_UpdatedTimestamp = Path.parse("./auditDetails/updatedTimestamp");
	} 

	// Table type path
	public final class _Years
	{
		private static final Path _Years = _Root.add("Years");
		public static Path getPathInSchema()
		{
			return _Years;
		}
		public static final Path _Year = Path.parse("./year");
		public static final Path _AuditDetails = Path.parse("./auditDetails");
		public static final Path _AuditDetails_CreatedBy = Path.parse("./auditDetails/createdBy");
		public static final Path _AuditDetails_CreatedTimestamp = Path.parse("./auditDetails/createdTimestamp");
		public static final Path _AuditDetails_UpdatedBy = Path.parse("./auditDetails/updatedBy");
		public static final Path _AuditDetails_UpdatedTimestamp = Path.parse("./auditDetails/updatedTimestamp");
		public static final Path _CategoryConfigurations = Path.parse("./CategoryConfigurations");
	} 

	// Table type path
	public final class _HalfYears
	{
		private static final Path _HalfYears = _Root.add("HalfYears");
		public static Path getPathInSchema()
		{
			return _HalfYears;
		}
		public static final Path _HalfYear = Path.parse("./HalfYear");
		public static final Path _AuditDetails = Path.parse("./auditDetails");
		public static final Path _AuditDetails_CreatedBy = Path.parse("./auditDetails/createdBy");
		public static final Path _AuditDetails_CreatedTimestamp = Path.parse("./auditDetails/createdTimestamp");
		public static final Path _AuditDetails_UpdatedBy = Path.parse("./auditDetails/updatedBy");
		public static final Path _AuditDetails_UpdatedTimestamp = Path.parse("./auditDetails/updatedTimestamp");
	} 

	// Table type path
	public final class _Quarters
	{
		private static final Path _Quarters = _Root.add("quarters");
		public static Path getPathInSchema()
		{
			return _Quarters;
		}
		public static final Path _Quarter = Path.parse("./quarter");
		public static final Path _AuditDetails = Path.parse("./auditDetails");
		public static final Path _AuditDetails_CreatedBy = Path.parse("./auditDetails/createdBy");
		public static final Path _AuditDetails_CreatedTimestamp = Path.parse("./auditDetails/createdTimestamp");
		public static final Path _AuditDetails_UpdatedBy = Path.parse("./auditDetails/updatedBy");
		public static final Path _AuditDetails_UpdatedTimestamp = Path.parse("./auditDetails/updatedTimestamp");
	} 

	// Table type path
	public final class _Months
	{
		private static final Path _Months = _Root.add("months");
		public static Path getPathInSchema()
		{
			return _Months;
		}
		public static final Path _Month = Path.parse("./month");
		public static final Path _AuditDetails = Path.parse("./auditDetails");
		public static final Path _AuditDetails_CreatedBy = Path.parse("./auditDetails/createdBy");
		public static final Path _AuditDetails_CreatedTimestamp = Path.parse("./auditDetails/createdTimestamp");
		public static final Path _AuditDetails_UpdatedBy = Path.parse("./auditDetails/updatedBy");
		public static final Path _AuditDetails_UpdatedTimestamp = Path.parse("./auditDetails/updatedTimestamp");
	} 

	// Table type path
	public final class _DataspaceConfigurations
	{
		private static final Path _DataspaceConfigurations = _Root.add("DataspaceConfigurations");
		public static Path getPathInSchema()
		{
			return _DataspaceConfigurations;
		}
		public static final Path _Dataspace = Path.parse("./dataspace");
		public static final Path _ParentDataspace = Path.parse("./parentDataspace");
		public static final Path _AuditDetails = Path.parse("./auditDetails");
		public static final Path _AuditDetails_CreatedBy = Path.parse("./auditDetails/createdBy");
		public static final Path _AuditDetails_CreatedTimestamp = Path.parse("./auditDetails/createdTimestamp");
		public static final Path _AuditDetails_UpdatedBy = Path.parse("./auditDetails/updatedBy");
		public static final Path _AuditDetails_UpdatedTimestamp = Path.parse("./auditDetails/updatedTimestamp");
	} 
	// ===============================================

}
