package com.cris.feedback.path;

import com.orchestranetworks.schema.*;

/**
 * Generated by TIBCO EBX(R) 1215:0003, at 2023/07/10 16:41:39 [CEST].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: Feedback, path: /WEB-INF\ebx\schemas\Feedback.xsd].
 * 
 * Root paths in this interface: 
 * 	'/root'   relativeToRoot: false
 * 
 */
public interface FeedbackPath
{
	// ===============================================
	// Constants for nodes under '/root'.
	// Statistics:
	//		23 path constants.
	//		12 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Root_Feedback
	{
		private static final Path _Root_Feedback = _Root.add("Feedback");
		public static Path getPathInSchema()
		{
			return _Root_Feedback;
		}
		public static final Path _Root_Feedback_Id = Path.parse("./id");
		public static final Path _Root_Feedback_UserId = Path.parse("./UserId");
		public static final Path _Root_Feedback_UserZone = Path.parse("./UserZone");
		public static final Path _Root_Feedback_UserName = Path.parse("./UserName");
		public static final Path _Root_Feedback_UserDivision = Path.parse("./UserDivision");
		public static final Path _Root_Feedback_UserDesignation = Path.parse("./UserDesignation");
		public static final Path _Root_Feedback_MobileNumber = Path.parse("./MobileNumber");
		public static final Path _Root_Feedback_RequestType = Path.parse("./RequestType");
		public static final Path _Root_Feedback_RequestPriority = Path.parse("./RequestPriority");
		public static final Path _Root_Feedback_ChooseFunctionality = Path.parse("./ChooseFunctionality");
		public static final Path _Root_Feedback_RequestTitle = Path.parse("./RequestTitle");
		public static final Path _Root_Feedback_RequestDescription = Path.parse("./RequestDescription");
	} 
	// ===============================================

}
