package com.bct.retailmodule;

import com.orchestranetworks.schema.*;

/**
 * Generated by TIBCO EBX(R) 1214:0002, at 2023/03/22 23:14:01 [CET].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: retail-module, path: /WEB-INF/ebx/RetailDataModel.xsd].
 * 
 * Root paths in this interface: 
 * 	'/root'   relativeToRoot: false
 * 
 */
public interface Paths
{
	// ===============================================
	// Constants for nodes under '/root'.
	// Prefix:  ''.
	// Statistics:
	//		79 path constants.
	//		27 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Store
	{
		private static final Path _Store = _Root.add("Store");
		public static Path getPathInSchema()
		{
			return _Store;
		}
		public static final Path _Identifier = Path.parse("./identifier");
		public static final Path _Inventories = Path.parse("./inventories");
		public static final Path _Name = Path.parse("./name");
		public static final Path _Type = Path.parse("./type");
		public static final Path _Address = Path.parse("./address");
		public static final Path _Address_Street = Path.parse("./address/street");
		public static final Path _Address_City = Path.parse("./address/city");
		public static final Path _Address_Region = Path.parse("./address/region");
		public static final Path _Address_Postcode = Path.parse("./address/postcode");
		public static final Path _Address_Country = Path.parse("./address/country");
	} 

	// Table type path
	public final class _Category
	{
		private static final Path _Category = _Root.add("Category");
		public static Path getPathInSchema()
		{
			return _Category;
		}
		public static final Path _Identifier = Path.parse("./identifier");
		public static final Path _Parent = Path.parse("./parent");
		public static final Path _Name = Path.parse("./name");
		public static final Path _Comment = Path.parse("./comment");
	} 

	// Table type path
	public final class _Brand
	{
		private static final Path _Brand = _Root.add("Brand");
		public static Path getPathInSchema()
		{
			return _Brand;
		}
		public static final Path _Identifier = Path.parse("./identifier");
		public static final Path _Name = Path.parse("./name");
	} 

	// Table type path
	public final class _Item
	{
		private static final Path _Item = _Root.add("Item");
		public static Path getPathInSchema()
		{
			return _Item;
		}
		public static final Path _Identifier = Path.parse("./identifier");
		public static final Path _Category = Path.parse("./category");
		public static final Path _Brand = Path.parse("./brand");
		public static final Path _Inventories = Path.parse("./inventories");
		public static final Path _Name = Path.parse("./name");
		public static final Path _Available = Path.parse("./available");
		public static final Path _DefaultPrice = Path.parse("./defaultPrice");
	} 

	// Table type path
	public final class _Inventory
	{
		private static final Path _Inventory = _Root.add("Inventory");
		public static Path getPathInSchema()
		{
			return _Inventory;
		}
		public static final Path _Item = Path.parse("./item");
		public static final Path _Store = Path.parse("./store");
		public static final Path _Stock = Path.parse("./stock");
		public static final Path _Price = Path.parse("./price");
		public static final Path _Modified = Path.parse("./modified");
	} 
	// ===============================================

}
