package com.cris.coach_master;

import com.orchestranetworks.schema.*;

/**
 * Generated by TIBCO EBX(R) 1214:0002, at 2023/03/22 23:14:01 [CET].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: coach_master, path: /WEB-INF/ebx/coach_master.xsd].
 * 
 * Root paths in this interface: 
 * 	'/root'   relativeToRoot: false
 * 
 */
public interface Paths
{
	// ===============================================
	// Constants for nodes under '/root'.
	// Statistics:
	//		158 path constants.
	//		113 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Root_Coach
	{
		private static final Path _Root_Coach = _Root.add("Coach");
		public static Path getPathInSchema()
		{
			return _Root_Coach;
		}
		public static final Path _Root_Coach_Coach_Id = Path.parse("./Coach_Id");
		public static final Path _Root_Coach_Coach_Number = Path.parse("./Coach_Number");
		public static final Path _Root_Coach_Coach_Type = Path.parse("./Coach_Type");
		public static final Path _Root_Coach_Owning_Rly = Path.parse("./Owning_Rly");
		public static final Path _Root_Coach_Owning_Div = Path.parse("./Owning_Div");
		public static final Path _Root_Coach_Owning_Depot = Path.parse("./Owning_Depot");
		public static final Path _Root_Coach_RFID_Tag = Path.parse("./RFID_Tag");
		public static final Path _Root_Coach_Coach_Status = Path.parse("./Coach_Status");
		public static final Path _Root_Coach_No_of_Berth = Path.parse("./No_of_Berth");
		public static final Path _Root_Coach_Coach_Gauge = Path.parse("./Coach_Gauge");
		public static final Path _Root_Coach_Tare_Weight = Path.parse("./Tare_Weight");
		public static final Path _Root_Coach_Max_Speed = Path.parse("./Max_Speed");
		public static final Path _Root_Coach_Fitness_Type = Path.parse("./Fitness_Type");
		public static final Path _Root_Coach_Bio_Toilet_Fitted = Path.parse("./Bio_Toilet_Fitted");
		public static final Path _Root_Coach_Coupling_Type = Path.parse("./Coupling_Type");
		public static final Path _Root_Coach_Built_Date = Path.parse("./Built_Date");
		public static final Path _Root_Coach_Manufacturer = Path.parse("./Manufacturer");
		public static final Path _Root_Coach_Commissioning_Date = Path.parse("./Commissioning_Date");
		public static final Path _Root_Coach_Condemnation_Date = Path.parse("./Condemnation_Date");
		public static final Path _Root_Coach_Condemnation_Authority = Path.parse("./Condemnation_Authority");
		public static final Path _Root_Coach_Seat_Layout_Variant_No = Path.parse("./Seat_Layout_Variant_No");
		public static final Path _Root_Coach_Coach_ac_flag = Path.parse("./coach_ac_flag");
		public static final Path _Root_Coach_Coach_category = Path.parse("./coach_category");
		public static final Path _Root_Coach_Factory_Turnout_Date = Path.parse("./Factory_Turnout_Date");
		public static final Path _Root_Coach_Power_Generation_Type = Path.parse("./Power_Generation_Type");
		public static final Path _Root_Coach_Nominated_Workshop = Path.parse("./Nominated_Workshop");
		public static final Path _Root_Coach_Audit_Info = Path.parse("./Audit_Info");
		public static final Path _Root_Coach_Audit_Info_Source_Record_Id = Path.parse("./Audit_Info/Source_Record_Id");
		public static final Path _Root_Coach_Audit_Info_Source_System_Name = Path.parse("./Audit_Info/Source_System_Name");
		public static final Path _Root_Coach_Audit_Info_Source_Event_Type = Path.parse("./Audit_Info/Source_Event_Type");
		public static final Path _Root_Coach_Audit_Info_Source_Updated_By = Path.parse("./Audit_Info/Source_Updated_By");
		public static final Path _Root_Coach_Audit_Info_Source_Updated_Time = Path.parse("./Audit_Info/Source_Updated_Time");
		public static final Path _Root_Coach_Audit_Info_Source_Record_Created_By = Path.parse("./Audit_Info/Source_Record_Created_By");
		public static final Path _Root_Coach_Audit_Info_Source_Record_Created_On = Path.parse("./Audit_Info/Source_Record_Created_On");
	} 

	// Table type path
	public final class _Root_Seat_Layout_Master
	{
		private static final Path _Root_Seat_Layout_Master = _Root.add("Seat_Layout_Master");
		public static Path getPathInSchema()
		{
			return _Root_Seat_Layout_Master;
		}
		public static final Path _Root_Seat_Layout_Master_Seat_Layout_Id = Path.parse("./Seat_Layout_Id");
		public static final Path _Root_Seat_Layout_Master_Layout_Variant_No = Path.parse("./Layout_Variant_No");
		public static final Path _Root_Seat_Layout_Master_Composite_Flag = Path.parse("./Composite_Flag");
		public static final Path _Root_Seat_Layout_Master_Coach_Class_First = Path.parse("./Coach_Class_First");
		public static final Path _Root_Seat_Layout_Master_Coach_Class_Second = Path.parse("./Coach_Class_Second");
		public static final Path _Root_Seat_Layout_Master_Total_Berth = Path.parse("./Total_Berth");
		public static final Path _Root_Seat_Layout_Master_Seating_Capacity_First = Path.parse("./Seating_Capacity_First");
		public static final Path _Root_Seat_Layout_Master_Seating_Capacity_Second = Path.parse("./Seating_Capacity_Second");
		public static final Path _Root_Seat_Layout_Master_Sleeping_Capacity_First = Path.parse("./Sleeping_Capacity_First");
		public static final Path _Root_Seat_Layout_Master_Sleeping_Capacity_Second = Path.parse("./Sleeping_Capacity_Second");
		public static final Path _Root_Seat_Layout_Master_Total_Deck = Path.parse("./Total_Deck");
		public static final Path _Root_Seat_Layout_Master_Seating_Layout_Drawing_No = Path.parse("./Seating_Layout_Drawing_No");
		public static final Path _Root_Seat_Layout_Master_Seating_Layout_Drawing_Location = Path.parse("./Seating_Layout_Drawing_Location");
		public static final Path _Root_Seat_Layout_Master_Seating_Layout_Gen_Date = Path.parse("./Seating_Layout_Gen_Date");
		public static final Path _Root_Seat_Layout_Master_Validity_Flag = Path.parse("./Validity_Flag");
		public static final Path _Root_Seat_Layout_Master_Seat_Details_Record_Count = Path.parse("./Seat_Details_Record_Count");
		public static final Path _Root_Seat_Layout_Master_Seat_layout_details = Path.parse("./seat_layout_details");
		public static final Path _Root_Seat_Layout_Master_Audit_Info = Path.parse("./Audit_Info");
		public static final Path _Root_Seat_Layout_Master_Audit_Info_Source_Record_Id = Path.parse("./Audit_Info/Source_Record_Id");
		public static final Path _Root_Seat_Layout_Master_Audit_Info_Source_System_Name = Path.parse("./Audit_Info/Source_System_Name");
		public static final Path _Root_Seat_Layout_Master_Audit_Info_Source_Event_Type = Path.parse("./Audit_Info/Source_Event_Type");
		public static final Path _Root_Seat_Layout_Master_Audit_Info_SeatLayoutDetails_ModDate = Path.parse("./Audit_Info/SeatLayoutDetails_ModDate");
	} 

	// Table type path
	public final class _Root_Seat_Layout_Details
	{
		private static final Path _Root_Seat_Layout_Details = _Root.add("Seat_Layout_Details");
		public static Path getPathInSchema()
		{
			return _Root_Seat_Layout_Details;
		}
		public static final Path _Root_Seat_Layout_Details_Seat_Layout_Id = Path.parse("./Seat_Layout_Id");
		public static final Path _Root_Seat_Layout_Details_Layout_Variant_No = Path.parse("./Layout_Variant_No");
		public static final Path _Root_Seat_Layout_Details_Coach_Class = Path.parse("./Coach_Class");
		public static final Path _Root_Seat_Layout_Details_Row_No = Path.parse("./Row_No");
		public static final Path _Root_Seat_Layout_Details_Col_No = Path.parse("./Col_No");
		public static final Path _Root_Seat_Layout_Details_Berth_No = Path.parse("./Berth_No");
		public static final Path _Root_Seat_Layout_Details_Berth_Qualifier = Path.parse("./Berth_Qualifier");
		public static final Path _Root_Seat_Layout_Details_Cabin_No = Path.parse("./Cabin_No");
		public static final Path _Root_Seat_Layout_Details_Cabin_Name = Path.parse("./Cabin_Name");
		public static final Path _Root_Seat_Layout_Details_Cabin_Coupe_Flag = Path.parse("./Cabin_Coupe_Flag");
		public static final Path _Root_Seat_Layout_Details_Berth_Serial_No = Path.parse("./Berth_Serial_No");
		public static final Path _Root_Seat_Layout_Details_Deck_Id = Path.parse("./Deck_Id");
		public static final Path _Root_Seat_Layout_Details_Passage_Flag = Path.parse("./Passage_Flag");
		public static final Path _Root_Seat_Layout_Details_Seat_Direction = Path.parse("./Seat_Direction");
		public static final Path _Root_Seat_Layout_Details_Audit_Info = Path.parse("./Audit_Info");
		public static final Path _Root_Seat_Layout_Details_Audit_Info_Source_Record_Id = Path.parse("./Audit_Info/Source_Record_Id");
		public static final Path _Root_Seat_Layout_Details_Audit_Info_Source_System_Name = Path.parse("./Audit_Info/Source_System_Name");
		public static final Path _Root_Seat_Layout_Details_Audit_Info_Source_Event_Type = Path.parse("./Audit_Info/Source_Event_Type");
	} 

	// Table type path
	public final class _Root_Coach_type
	{
		private static final Path _Root_Coach_type = _Root.add("coach_type");
		public static Path getPathInSchema()
		{
			return _Root_Coach_type;
		}
		public static final Path _Root_Coach_type_Coach_type = Path.parse("./coach_type");
		public static final Path _Root_Coach_type_Brake_type = Path.parse("./brake_type");
		public static final Path _Root_Coach_type_Coupling_type = Path.parse("./coupling_type");
		public static final Path _Root_Coach_type_Power_generation_type = Path.parse("./power_generation_type");
		public static final Path _Root_Coach_type_Coach_type_description = Path.parse("./coach_type_description");
		public static final Path _Root_Coach_type_Vehicle_type = Path.parse("./vehicle_type");
		public static final Path _Root_Coach_type_Coach_category = Path.parse("./coach_category");
		public static final Path _Root_Coach_type_Gauge = Path.parse("./gauge");
		public static final Path _Root_Coach_type_Coach_capacity = Path.parse("./coach_capacity");
		public static final Path _Root_Coach_type_Reserved_flag = Path.parse("./reserved_flag");
		public static final Path _Root_Coach_type_Prs_bogie_id = Path.parse("./prs_bogie_id");
		public static final Path _Root_Coach_type_Tare_weight = Path.parse("./tare_weight");
		public static final Path _Root_Coach_type_Max_speed = Path.parse("./max_speed");
		public static final Path _Root_Coach_type_Composit_flag = Path.parse("./composit_flag");
		public static final Path _Root_Coach_type_Composit_class = Path.parse("./composit_class");
		public static final Path _Root_Coach_type_Bogie_type = Path.parse("./bogie_type");
		public static final Path _Root_Coach_type_Coach_class = Path.parse("./coach_class");
		public static final Path _Root_Coach_type_Second_prs_id = Path.parse("./second_prs_id");
		public static final Path _Root_Coach_type_First_prs_id = Path.parse("./first_prs_id");
		public static final Path _Root_Coach_type_Coach_volts = Path.parse("./coach_volts");
		public static final Path _Root_Coach_type_Double_decker_flag = Path.parse("./double_decker_flag");
		public static final Path _Root_Coach_type_Failure_class = Path.parse("./failure_class");
		public static final Path _Root_Coach_type_Coach_vestibule = Path.parse("./coach_vestibule");
		public static final Path _Root_Coach_type_Coach_ac_flag = Path.parse("./coach_ac_flag");
		public static final Path _Root_Coach_type_Prs_class = Path.parse("./prs_class");
		public static final Path _Root_Coach_type_Prs_id = Path.parse("./prs_id");
		public static final Path _Root_Coach_type_Second_prs_class = Path.parse("./second_prs_class");
		public static final Path _Root_Coach_type_First_prs_class = Path.parse("./first_prs_class");
		public static final Path _Root_Coach_type_First_no_of_births = Path.parse("./first_no_of_births");
		public static final Path _Root_Coach_type_First_no_of_seats = Path.parse("./first_no_of_seats");
		public static final Path _Root_Coach_type_Second_no_of_seats = Path.parse("./second_no_of_seats");
		public static final Path _Root_Coach_type_Second_no_of_berths = Path.parse("./second_no_of_berths");
		public static final Path _Root_Coach_type_Shell_type = Path.parse("./shell_type");
		public static final Path _Root_Coach_type_Parcel_flag = Path.parse("./parcel_flag");
		public static final Path _Root_Coach_type_Coach_type_class = Path.parse("./coach_type_class");
		public static final Path _Root_Coach_type_Major_head = Path.parse("./major_head");
		public static final Path _Root_Coach_type_Coach_major_class = Path.parse("./coach_major_class");
		public static final Path _Root_Coach_type_Coach_category_rb = Path.parse("./coach_category_rb");
		public static final Path _Root_Coach_type_Linen_facility = Path.parse("./linen_facility");
		public static final Path _Root_Coach_type_Audit_Info = Path.parse("./Audit_Info");
		public static final Path _Root_Coach_type_Audit_Info_Source_Record_Id = Path.parse("./Audit_Info/Source_Record_Id");
		public static final Path _Root_Coach_type_Audit_Info_Source_System_Name = Path.parse("./Audit_Info/Source_System_Name");
		public static final Path _Root_Coach_type_Audit_Info_Source_Event_Type = Path.parse("./Audit_Info/Source_Event_Type");
	} 
	// ===============================================

}
