package com.bct.crismodule;

import com.orchestranetworks.schema.*;

/**
 * Generated by TIBCO EBX(R) 1214:0002, at 2023/03/22 23:14:01 [CET].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: cris-module, path: /WEB-INF/ebx/CRISDataModel.xsd].
 * 
 * Root paths in this interface: 
 * 	'/root'   relativeToRoot: false
 * 
 */
public interface Paths
{
	// ===============================================
	// Constants for nodes under '/root'.
	// Prefix:  ''.
	// Statistics:
	//		65 path constants.
	//		22 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Station
	{
		private static final Path _Station = _Root.add("station");
		public static Path getPathInSchema()
		{
			return _Station;
		}
		public static final Path _Tab1 = Path.parse("./tab1");
		public static final Path _Tab1_Stn_code = Path.parse("./tab1/stn_code");
		public static final Path _Tab1_Stn_name = Path.parse("./tab1/stn_name");
		public static final Path _Tab1_Code_name = Path.parse("./tab1/code_name");
		public static final Path _Tab1_Zone = Path.parse("./tab1/zone");
		public static final Path _Tab1_Division = Path.parse("./tab1/division");
		public static final Path _Tab1_Gauge_type = Path.parse("./tab1/gauge_type");
		public static final Path _Tab1_Traffic_type = Path.parse("./tab1/traffic_type");
		public static final Path _Tab1_Halt_flag = Path.parse("./tab1/halt_flag");
		public static final Path _Tab2 = Path.parse("./tab2");
		public static final Path _Tab2_Latitude = Path.parse("./tab2/latitude");
		public static final Path _Tab2_Longitude = Path.parse("./tab2/longitude");
	} 

	// Table type path
	public final class _Division
	{
		private static final Path _Division = _Root.add("division");
		public static Path getPathInSchema()
		{
			return _Division;
		}
		public static final Path _Div_code = Path.parse("./div_code");
		public static final Path _Div_name = Path.parse("./div_name");
		public static final Path _Zone = Path.parse("./zone");
		public static final Path _Stn_div_association = Path.parse("./stn_div_association");
	} 

	// Table type path
	public final class _Zone
	{
		private static final Path _Zone = _Root.add("zone");
		public static Path getPathInSchema()
		{
			return _Zone;
		}
		public static final Path _Zone_code = Path.parse("./zone_code");
		public static final Path _Zone_name = Path.parse("./zone_name");
		public static final Path _Div_zone_association = Path.parse("./div_zone_association");
		public static final Path _Stn_zone_association = Path.parse("./stn_zone_association");
	} 

	// Table type path
	public final class _Total_count
	{
		private static final Path _Total_count = _Root.add("total_count");
		public static Path getPathInSchema()
		{
			return _Total_count;
		}
		public static final Path _Total_station = Path.parse("./total_station");
		public static final Path _Total_division = Path.parse("./total_division");
		public static final Path _Total_zone = Path.parse("./total_zone");
		public static final Path _Total_pk = Path.parse("./total_pk");
	} 
	// ===============================================

}
