package com.cris.loco_landing;

import com.orchestranetworks.schema.*;

/**
 * Generated by TIBCO EBX(R) 1214:0002, at 2023/03/22 23:14:01 [CET].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: loco_landing, path: /WEB-INF/ebx/loco_landing.xsd].
 * 
 * Root paths in this interface: 
 * 	'/root'   relativeToRoot: false
 * 
 */
public interface Paths
{
	// ===============================================
	// Constants for nodes under '/root'.
	// Statistics:
	//		93 path constants.
	//		62 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Root_Loco_Fois
	{
		private static final Path _Root_Loco_Fois = _Root.add("Loco_Fois");
		public static Path getPathInSchema()
		{
			return _Root_Loco_Fois;
		}
		public static final Path _Root_Loco_Fois_Owing_Rly = Path.parse("./Owing_Rly");
		public static final Path _Root_Loco_Fois_Base_Shed = Path.parse("./Base_Shed");
		public static final Path _Root_Loco_Fois_Loco_Number = Path.parse("./Loco_Number");
		public static final Path _Root_Loco_Fois_Loco_Type = Path.parse("./Loco_Type");
		public static final Path _Root_Loco_Fois_Domain = Path.parse("./Domain");
	} 

	// Table type path
	public final class _Root_Loco_Lmdm
	{
		private static final Path _Root_Loco_Lmdm = _Root.add("Loco_Lmdm");
		public static Path getPathInSchema()
		{
			return _Root_Loco_Lmdm;
		}
		public static final Path _Root_Loco_Lmdm_Loco_Number = Path.parse("./Loco_Number");
		public static final Path _Root_Loco_Lmdm_Loco_Type = Path.parse("./Loco_Type");
		public static final Path _Root_Loco_Lmdm_Loco_Commissioning_Date = Path.parse("./Loco_Commissioning_Date");
		public static final Path _Root_Loco_Lmdm_Loco_Owning_Zone = Path.parse("./Loco_Owning_Zone");
		public static final Path _Root_Loco_Lmdm_Loco_Owning_Shed = Path.parse("./Loco_Owning_Shed");
		public static final Path _Root_Loco_Lmdm_Loco_Manufacturing_Date = Path.parse("./Loco_Manufacturing_Date");
		public static final Path _Root_Loco_Lmdm_Loco_Receiving_Date = Path.parse("./Loco_Receiving_Date");
		public static final Path _Root_Loco_Lmdm_Loco_Manufacturer = Path.parse("./Loco_Manufacturer");
		public static final Path _Root_Loco_Lmdm_Loco_Axle_Load = Path.parse("./Loco_Axle_Load");
		public static final Path _Root_Loco_Lmdm_Loco_Axle_Load_Unit = Path.parse("./Loco_Axle_Load_Unit");
		public static final Path _Root_Loco_Lmdm_Loco_Traction_Motor_Type = Path.parse("./Loco_Traction_Motor_Type");
		public static final Path _Root_Loco_Lmdm_Loco_Hauling_Power = Path.parse("./Loco_Hauling_Power");
		public static final Path _Root_Loco_Lmdm_Loco_Traction_Code = Path.parse("./Loco_Traction_Code");
		public static final Path _Root_Loco_Lmdm_Loco_Brake_Type = Path.parse("./Loco_Brake_Type");
		public static final Path _Root_Loco_Lmdm_Loco_Brake_Sub_Type = Path.parse("./Loco_Brake_Sub_Type");
		public static final Path _Root_Loco_Lmdm_Loco_Control_Type = Path.parse("./Loco_Control_Type");
		public static final Path _Root_Loco_Lmdm_Loco_Permanent_Domain = Path.parse("./Loco_Permanent_Domain");
		public static final Path _Root_Loco_Lmdm_Loco_Gauge_Type = Path.parse("./Loco_Gauge_Type");
		public static final Path _Root_Loco_Lmdm_Loco_Lease_Type = Path.parse("./Loco_Lease_Type");
		public static final Path _Root_Loco_Lmdm_Loco_Auxilary = Path.parse("./Loco_Auxilary");
		public static final Path _Root_Loco_Lmdm_Loco_Boogie_Type = Path.parse("./Loco_Boogie_Type");
		public static final Path _Root_Loco_Lmdm_Loco_Cab1_AC = Path.parse("./Loco_Cab1_AC");
		public static final Path _Root_Loco_Lmdm_Loco_Hotel_Load = Path.parse("./Loco_Hotel_Load");
		public static final Path _Root_Loco_Lmdm_Is_Gps_Enabled = Path.parse("./Is_Gps_Enabled");
		public static final Path _Root_Loco_Lmdm_Flag_Type = Path.parse("./Flag_Type");
		public static final Path _Root_Loco_Lmdm_Loco_Entry_Date = Path.parse("./Loco_Entry_Date");
	} 

	// Table type path
	public final class _Root_Loco_Slam
	{
		private static final Path _Root_Loco_Slam = _Root.add("Loco_Slam");
		public static Path getPathInSchema()
		{
			return _Root_Loco_Slam;
		}
		public static final Path _Root_Loco_Slam_Loco_Number = Path.parse("./Loco_Number");
		public static final Path _Root_Loco_Slam_Loco_Type = Path.parse("./Loco_Type");
		public static final Path _Root_Loco_Slam_Loco_Commissioning_Date = Path.parse("./Loco_Commissioning_Date");
		public static final Path _Root_Loco_Slam_Loco_Owning_Zone = Path.parse("./Loco_Owning_Zone");
		public static final Path _Root_Loco_Slam_Loco_Owning_Shed = Path.parse("./Loco_Owning_Shed");
		public static final Path _Root_Loco_Slam_Loco_Owning_Division = Path.parse("./Loco_Owning_Division");
		public static final Path _Root_Loco_Slam_Loco_Manufacturing_Date = Path.parse("./Loco_Manufacturing_Date");
		public static final Path _Root_Loco_Slam_Loco_Receiving_Date = Path.parse("./Loco_Receiving_Date");
		public static final Path _Root_Loco_Slam_Loco_Manufacturer = Path.parse("./Loco_Manufacturer");
		public static final Path _Root_Loco_Slam_Loco_Axle_Load = Path.parse("./Loco_Axle_Load");
		public static final Path _Root_Loco_Slam_Loco_Traction_Motor_Type = Path.parse("./Loco_Traction_Motor_Type");
		public static final Path _Root_Loco_Slam_Loco_Traction_Code = Path.parse("./Loco_Traction_Code");
		public static final Path _Root_Loco_Slam_Loco_Brake_Type = Path.parse("./Loco_Brake_Type");
		public static final Path _Root_Loco_Slam_Loco_Control_Type = Path.parse("./Loco_Control_Type");
		public static final Path _Root_Loco_Slam_Loco_Nomination = Path.parse("./Loco_Nomination");
		public static final Path _Root_Loco_Slam_Loco_Permanent_Domain = Path.parse("./Loco_Permanent_Domain");
		public static final Path _Root_Loco_Slam_Loco_Gauge_Type = Path.parse("./Loco_Gauge_Type");
		public static final Path _Root_Loco_Slam_Loco_Auxilary = Path.parse("./Loco_Auxilary");
		public static final Path _Root_Loco_Slam_Loco_Boogie_Type = Path.parse("./Loco_Boogie_Type");
		public static final Path _Root_Loco_Slam_Loco_Cab1_AC = Path.parse("./Loco_Cab1_AC");
		public static final Path _Root_Loco_Slam_Loco_Hlc = Path.parse("./Loco_Hlc");
		public static final Path _Root_Loco_Slam_Loco_Status = Path.parse("./Loco_Status");
		public static final Path _Root_Loco_Slam_Loco_Rtis_Flag = Path.parse("./Loco_Rtis_Flag");
		public static final Path _Root_Loco_Slam_Loco_Remmlot_Flag = Path.parse("./Loco_Remmlot_Flag");
		public static final Path _Root_Loco_Slam_Loco_Cab2_AC = Path.parse("./Loco_Cab2_AC");
		public static final Path _Root_Loco_Slam_Loco_Brake_Sub_Type = Path.parse("./Loco_Brake_Sub_Type");
		public static final Path _Root_Loco_Slam_Loco_POH_Date = Path.parse("./Loco_POH_Date");
		public static final Path _Root_Loco_Slam_Loco_HRP_Flag = Path.parse("./Loco_HRP_Flag");
		public static final Path _Root_Loco_Slam_Loco_HRP2_Flag = Path.parse("./Loco_HRP2_Flag");
		public static final Path _Root_Loco_Slam_Loco_CVVRS_Type = Path.parse("./Loco_CVVRS_Type");
		public static final Path _Root_Loco_Slam_Loco_VCD_Flag = Path.parse("./Loco_VCD_Flag");
	} 
	// ===============================================

}
