package com.cris.wagon_master.paths;

import com.orchestranetworks.schema.*;

/**
 * Generated by TIBCO EBX(R) 1214:0002, at 2023/03/22 23:14:01 [CET].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: wagon_master, path: /WEB-INF/ebx/schemas/wagon-master-data-model.xsd].
 * 
 * Root paths in this interface: 
 * 	'/root'   relativeToRoot: false
 * 
 */
public interface WagonPaths
{
	// ===============================================
	// Constants for nodes under '/root'.
	// Statistics:
	//		183 path constants.
	//		116 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Root_Wagon
	{
		private static final Path _Root_Wagon = _Root.add("Wagon");
		public static Path getPathInSchema()
		{
			return _Root_Wagon;
		}
		public static final Path _Root_Wagon_Wagon_Id = Path.parse("./Wagon_Id");
		public static final Path _Root_Wagon_Wagon_Number = Path.parse("./Wagon_Number");
		public static final Path _Root_Wagon_Wagon_Organization_Type = Path.parse("./Wagon_Organization_Type");
		public static final Path _Root_Wagon_Wagon_Type = Path.parse("./Wagon_Type");
		public static final Path _Root_Wagon_Wagon_Owning_Railway = Path.parse("./Wagon_Owning_Railway");
		public static final Path _Root_Wagon_Wagon_Base_Depot = Path.parse("./Wagon_Base_Depot");
		public static final Path _Root_Wagon_Wagon_Rfid1 = Path.parse("./Wagon_Rfid1");
		public static final Path _Root_Wagon_Wagon_Rfid2 = Path.parse("./Wagon_Rfid2");
		public static final Path _Root_Wagon_Wagon_Class_Group = Path.parse("./Wagon_Class_Group");
		public static final Path _Root_Wagon_Wagon_Tare = Path.parse("./Wagon_Tare");
		public static final Path _Root_Wagon_Wagon_Carrying_Capacity = Path.parse("./Wagon_Carrying_Capacity");
		public static final Path _Root_Wagon_Wagon_Scheme_Name = Path.parse("./Wagon_Scheme_Name");
		public static final Path _Root_Wagon_Wagon_Manufacturer = Path.parse("./Wagon_Manufacturer");
		public static final Path _Root_Wagon_Wagon_Status = Path.parse("./Wagon_Status");
		public static final Path _Root_Wagon_Wagon_Remarks = Path.parse("./Wagon_Remarks");
		public static final Path _Root_Wagon_Wagon_Purchase_Order_Number = Path.parse("./Wagon_Purchase_Order_Number");
		public static final Path _Root_Wagon_Wagon_Manufacture_Date = Path.parse("./Wagon_Manufacture_Date");
		public static final Path _Root_Wagon_Wagon_Gauge_Code = Path.parse("./Wagon_Gauge_Code");
		public static final Path _Root_Wagon_Wagon_Condemnation_Authority = Path.parse("./Wagon_Condemnation_Authority");
		public static final Path _Root_Wagon_Wagon_Condemnation_Authority_Number = Path.parse("./Wagon_Condemnation_Authority_Number");
		public static final Path _Root_Wagon_Wagon_Condemnation_Authority_Date = Path.parse("./Wagon_Condemnation_Authority_Date");
		public static final Path _Root_Wagon_Wagon_Condemnation_Date = Path.parse("./Wagon_Condemnation_Date");
		public static final Path _Root_Wagon_Wagon_Number_Old = Path.parse("./Wagon_Number_Old");
		public static final Path _Root_Wagon_Wagon_Valid_Flag = Path.parse("./Wagon_Valid_Flag");
		public static final Path _Root_Wagon_Wagon_Alloted_By = Path.parse("./Wagon_Alloted_By");
		public static final Path _Root_Wagon_Wagon_Allotment_Letter_Number = Path.parse("./Wagon_Allotment_Letter_Number");
		public static final Path _Root_Wagon_Wagon_Allotment_Date = Path.parse("./Wagon_Allotment_Date");
		public static final Path _Root_Wagon_Wagon_ROH_Repair_Station = Path.parse("./Wagon_ROH_Repair_Station");
		public static final Path _Root_Wagon_Wagon_ROH_Date = Path.parse("./Wagon_ROH_Date");
		public static final Path _Root_Wagon_Wagon_Record_Status = Path.parse("./Wagon_Record_Status");
		public static final Path _Root_Wagon_Wagon_Update_Number_Type_Owner = Path.parse("./Wagon_Update_Number_Type_Owner");
		public static final Path _Root_Wagon_Wagon_Inspecting_Added_Organization = Path.parse("./Wagon_Inspecting_Added_Organization");
		public static final Path _Root_Wagon_Wagon_POH_Date = Path.parse("./Wagon_POH_Date");
		public static final Path _Root_Wagon_Wagon_POH_Station = Path.parse("./Wagon_POH_Station");
		public static final Path _Root_Wagon_Audit_info = Path.parse("./Audit_info");
		public static final Path _Root_Wagon_Audit_info_Source_Record_Id = Path.parse("./Audit_info/Source_Record_Id");
		public static final Path _Root_Wagon_Audit_info_Source_System_Name = Path.parse("./Audit_info/Source_System_Name");
		public static final Path _Root_Wagon_Audit_info_Source_Event_Type = Path.parse("./Audit_info/Source_Event_Type");
		public static final Path _Root_Wagon_Audit_info_Received_Timestamp = Path.parse("./Audit_info/Received_Timestamp");
		public static final Path _Root_Wagon_Audit_info_Logged_In_User = Path.parse("./Audit_info/Logged_In_User");
		public static final Path _Root_Wagon_Audit_info_In_Workflow = Path.parse("./Audit_info/In_Workflow");
	} 

	// Table type path
	public final class _Root_Wagon_Type
	{
		private static final Path _Root_Wagon_Type = _Root.add("Wagon_Type");
		public static Path getPathInSchema()
		{
			return _Root_Wagon_Type;
		}
		public static final Path _Root_Wagon_Type_Wagon_Type = Path.parse("./Wagon_Type");
		public static final Path _Root_Wagon_Type_Wagon_Type_Description = Path.parse("./Wagon_Type_Description");
		public static final Path _Root_Wagon_Type_Wagon_Class_Group = Path.parse("./Wagon_Class_Group");
		public static final Path _Root_Wagon_Type_Wagon_Numerical_Code = Path.parse("./Wagon_Numerical_Code");
		public static final Path _Root_Wagon_Type_Wagon_Carrying_Capacity = Path.parse("./Wagon_Carrying_Capacity");
		public static final Path _Root_Wagon_Type_Wagon_Tare = Path.parse("./Wagon_Tare");
		public static final Path _Root_Wagon_Type_Wagon_Axle_Load = Path.parse("./Wagon_Axle_Load");
		public static final Path _Root_Wagon_Type_Wagon_Bearing_Type = Path.parse("./Wagon_Bearing_Type");
		public static final Path _Root_Wagon_Type_Wagon_Coupling_Type = Path.parse("./Wagon_Coupling_Type");
		public static final Path _Root_Wagon_Type_Wagon_Boggie_Type = Path.parse("./Wagon_Boggie_Type");
		public static final Path _Root_Wagon_Type_Wagon_Brake_Type = Path.parse("./Wagon_Brake_Type");
		public static final Path _Root_Wagon_Type_Wagon_First_Poh_Duration = Path.parse("./Wagon_First_Poh_Duration");
		public static final Path _Root_Wagon_Type_Wagon_Next_Poh_Duration = Path.parse("./Wagon_Next_Poh_Duration");
		public static final Path _Root_Wagon_Type_Wagon_First_Roh_Duration = Path.parse("./Wagon_First_Roh_Duration");
		public static final Path _Root_Wagon_Type_Wagon_Next_Roh_Duration = Path.parse("./Wagon_Next_Roh_Duration");
		public static final Path _Root_Wagon_Type_Wagon_Codal_Life = Path.parse("./Wagon_Codal_Life");
		public static final Path _Root_Wagon_Type_Wagon_Gauge = Path.parse("./Wagon_Gauge");
		public static final Path _Root_Wagon_Type_Wagon_Type_Display_Name = Path.parse("./Wagon_Type_Display_Name");
		public static final Path _Root_Wagon_Type_Wagon_Type_Valid_Flag = Path.parse("./Wagon_Type_Valid_Flag");
		public static final Path _Root_Wagon_Type_Wagon_Rake_Type = Path.parse("./Wagon_Rake_Type");
		public static final Path _Root_Wagon_Type_Wagon_stock_type = Path.parse("./Wagon_stock_type");
		public static final Path _Root_Wagon_Type_Audit_Info = Path.parse("./Audit_Info");
		public static final Path _Root_Wagon_Type_Audit_Info_Source_Record_Id = Path.parse("./Audit_Info/Source_Record_Id");
		public static final Path _Root_Wagon_Type_Audit_Info_Source_System_Name = Path.parse("./Audit_Info/Source_System_Name");
		public static final Path _Root_Wagon_Type_Audit_Info_Source_Event_Type = Path.parse("./Audit_Info/Source_Event_Type");
	} 

	// Table type path
	public final class _Root_Wagon_ROH_Depot
	{
		private static final Path _Root_Wagon_ROH_Depot = _Root.add("Wagon_ROH_Depot");
		public static Path getPathInSchema()
		{
			return _Root_Wagon_ROH_Depot;
		}
		public static final Path _Root_Wagon_ROH_Depot_Zone = Path.parse("./Zone");
		public static final Path _Root_Wagon_ROH_Depot_Division = Path.parse("./Division");
		public static final Path _Root_Wagon_ROH_Depot_Depot = Path.parse("./Depot");
		public static final Path _Root_Wagon_ROH_Depot_Organisation_Type = Path.parse("./Organisation_Type");
		public static final Path _Root_Wagon_ROH_Depot_Organisation_Serial_Number = Path.parse("./Organisation_Serial_Number");
		public static final Path _Root_Wagon_ROH_Depot_Valid_Flag = Path.parse("./Valid_Flag");
		public static final Path _Root_Wagon_ROH_Depot_Audit_Info = Path.parse("./Audit_Info");
		public static final Path _Root_Wagon_ROH_Depot_Audit_Info_Source_Record_Id = Path.parse("./Audit_Info/Source_Record_Id");
		public static final Path _Root_Wagon_ROH_Depot_Audit_Info_Source_System_Name = Path.parse("./Audit_Info/Source_System_Name");
		public static final Path _Root_Wagon_ROH_Depot_Audit_Info_Source_Event_Type = Path.parse("./Audit_Info/Source_Event_Type");
	} 

	// Table type path
	public final class _Root_Wagon_Allotment_Scheme
	{
		private static final Path _Root_Wagon_Allotment_Scheme = _Root.add("Wagon_Allotment_Scheme");
		public static Path getPathInSchema()
		{
			return _Root_Wagon_Allotment_Scheme;
		}
		public static final Path _Root_Wagon_Allotment_Scheme_Scheme_Id = Path.parse("./Scheme_Id");
		public static final Path _Root_Wagon_Allotment_Scheme_Scheme_Name = Path.parse("./Scheme_Name");
		public static final Path _Root_Wagon_Allotment_Scheme_Maintenance_Criterion = Path.parse("./Maintenance_Criterion");
		public static final Path _Root_Wagon_Allotment_Scheme_Description = Path.parse("./description");
		public static final Path _Root_Wagon_Allotment_Scheme_Create_User = Path.parse("./Create_User");
		public static final Path _Root_Wagon_Allotment_Scheme_Create_Timestamp = Path.parse("./Create_Timestamp");
		public static final Path _Root_Wagon_Allotment_Scheme_Start_Date = Path.parse("./Start_Date");
		public static final Path _Root_Wagon_Allotment_Scheme_Update_User = Path.parse("./Update_User");
		public static final Path _Root_Wagon_Allotment_Scheme_Update_Timestamp = Path.parse("./Update_Timestamp");
		public static final Path _Root_Wagon_Allotment_Scheme_Status = Path.parse("./Status");
		public static final Path _Root_Wagon_Allotment_Scheme_Valid_Flag = Path.parse("./Valid_Flag");
		public static final Path _Root_Wagon_Allotment_Scheme_Platform = Path.parse("./Platform");
		public static final Path _Root_Wagon_Allotment_Scheme_Organisation_Serialno = Path.parse("./Organisation_Serialno");
		public static final Path _Root_Wagon_Allotment_Scheme_Audit_Info = Path.parse("./Audit_Info");
		public static final Path _Root_Wagon_Allotment_Scheme_Audit_Info_Source_Record_Id = Path.parse("./Audit_Info/Source_Record_Id");
		public static final Path _Root_Wagon_Allotment_Scheme_Audit_Info_Source_System_Name = Path.parse("./Audit_Info/Source_System_Name");
		public static final Path _Root_Wagon_Allotment_Scheme_Audit_Info_Source_Event_Type = Path.parse("./Audit_Info/Source_Event_Type");
	} 

	// Table type path
	public final class _Root_Wagon_Owner
	{
		private static final Path _Root_Wagon_Owner = _Root.add("Wagon_Owner");
		public static Path getPathInSchema()
		{
			return _Root_Wagon_Owner;
		}
		public static final Path _Root_Wagon_Owner_Owner_Id = Path.parse("./Owner_Id");
		public static final Path _Root_Wagon_Owner_Owner_Name = Path.parse("./Owner_Name");
		public static final Path _Root_Wagon_Owner_Numeric_Code = Path.parse("./Numeric_Code");
		public static final Path _Root_Wagon_Owner_Address = Path.parse("./Address");
		public static final Path _Root_Wagon_Owner_Type = Path.parse("./Type");
		public static final Path _Root_Wagon_Owner_Audit_Info = Path.parse("./Audit_Info");
		public static final Path _Root_Wagon_Owner_Audit_Info_Source_Record_Id = Path.parse("./Audit_Info/Source_Record_Id");
		public static final Path _Root_Wagon_Owner_Audit_Info_Source_System_Name = Path.parse("./Audit_Info/Source_System_Name");
		public static final Path _Root_Wagon_Owner_Audit_Info_Source_Event_Type = Path.parse("./Audit_Info/Source_Event_Type");
	} 

	// Table type path
	public final class _Root_Wagon_Manufacturer
	{
		private static final Path _Root_Wagon_Manufacturer = _Root.add("Wagon_Manufacturer");
		public static Path getPathInSchema()
		{
			return _Root_Wagon_Manufacturer;
		}
		public static final Path _Root_Wagon_Manufacturer_Org_SlNo = Path.parse("./Org_SlNo");
		public static final Path _Root_Wagon_Manufacturer_Organization_Code = Path.parse("./Organization_Code");
		public static final Path _Root_Wagon_Manufacturer_Organization_Type = Path.parse("./Organization_Type");
		public static final Path _Root_Wagon_Manufacturer_Organization_Description = Path.parse("./Organization_Description");
		public static final Path _Root_Wagon_Manufacturer_Organization_Sequence = Path.parse("./Organization_Sequence");
		public static final Path _Root_Wagon_Manufacturer_PRNT_ORG_SLNO = Path.parse("./PRNT_ORG_SLNO");
		public static final Path _Root_Wagon_Manufacturer_Num_Code = Path.parse("./Num_Code");
		public static final Path _Root_Wagon_Manufacturer_PVT_RLY = Path.parse("./PVT_RLY");
		public static final Path _Root_Wagon_Manufacturer_Created_By = Path.parse("./Created_By");
		public static final Path _Root_Wagon_Manufacturer_Created_On = Path.parse("./Created_On");
		public static final Path _Root_Wagon_Manufacturer_Valid_Flag = Path.parse("./Valid_Flag");
		public static final Path _Root_Wagon_Manufacturer_Manufacturer = Path.parse("./Manufacturer");
		public static final Path _Root_Wagon_Manufacturer_Station_Name = Path.parse("./Station_Name");
		public static final Path _Root_Wagon_Manufacturer_Man_Power_Flag = Path.parse("./Man_Power_Flag");
		public static final Path _Root_Wagon_Manufacturer_MF_RECV_RLY = Path.parse("./MF_RECV_RLY");
		public static final Path _Root_Wagon_Manufacturer_DISPATCH_FOR_FLAG = Path.parse("./DISPATCH_FOR_FLAG");
		public static final Path _Root_Wagon_Manufacturer_Audit_Info = Path.parse("./Audit_Info");
		public static final Path _Root_Wagon_Manufacturer_Audit_Info_Source_Record_Id = Path.parse("./Audit_Info/Source_Record_Id");
		public static final Path _Root_Wagon_Manufacturer_Audit_Info_Source_System_Name = Path.parse("./Audit_Info/Source_System_Name");
		public static final Path _Root_Wagon_Manufacturer_Audit_Info_Source_Event_Type = Path.parse("./Audit_Info/Source_Event_Type");
	} 
	// ===============================================

}
